CREATE TABLE IF NOT EXISTS urls (
	id TEXT PRIMARY KEY,
	original_url TEXT UNIQUE NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_urls_id ON urls (id);
